### Trigger workflow

POST https://api.github.com/repos/miroadamy-practice/github-actions-demo-1/dispatches
Content-Type:  application/vnd.github+json" \ 
Authorization: token {{ghtoken}}

{"event_type":"on_demand_test","client_payload":{"unit":false,"integration":true, "env": "production"}}


### Create Issue

POST https://api.github.com/repos/miroadamy-practice/github-actions-demo-1/dispatches
Content-Type:  application/vnd.github+json" \ 
Authorization: token {{ghtoken}}

{"event_type":"create_issue","client_payload":{"unit":false,"integration":true, "env": "production"}}

### Update repo

POST https://api.github.com/repos/miroadamy-practice/github-actions-demo-1/dispatches
Content-Type:  application/vnd.github+json" \ 
Authorization: token {{ghtoken}}

{"event_type":"modify_repo","client_payload":{"unit":false,"integration":true, "env": "production"}}
